### ISSUE TITLE
MKOB: Add 'config' menu item and dialog

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#169]
Provide a 'Configure' menu item and dialog to allow setting the configuration options. Currently, the options must be set using `Configure.py` (or command shortcuts).

It would be nice if the configure dialog had the ability to show all of the system/Python information that `Configure.py` allows. With that, 'Configure' wouldn't need to be packaged in the bundle - making the bundle build process much simpler.

**Comment by pwdirks** [comment]
I've started working on a "Config" or "Preferences" dialog.  Right now, the preferences panel code in my local branch shows up the following (on a Mac - this is TkInter so it’ll look differently on different platforms):

![image](https://user-images.githubusercontent.com/48630827/103922485-aa8d4b80-50c8-11eb-8e1f-e6c1cfc8397c.png)

All of these are being pulled from current config info at at initialization and saved as new config info on ’Save’.

I believe there are not currently any config options corresponding to an “Automatically connect at startup” setting or the “Hardware Interface” (None/GPIO/Serial port) setting?  I'll file a separate issue for that.

**Comment by pwdirks** [comment]
Filed issue #223 for the missing config options.

**Comment by AESilky** [comment]
That looks great!

A few questions/thoughts...
1. What is 'Local Interface' at the top indicating?
2. I'm not sure 'Transmit to remote stations' is currently implemented in the code. I certainly is in `config.py` and can be set/displayed with `Configure.py`, but I think that currently, if you are connected to a wire the code is sent. What do we expect this option to be used for (a use-case)?
3. The 'Repeat Key Locally' reminded me that I need to take that into account in the changes I'm making to handle the key closer. If 'Repeat Key Locally' is 'off' than in Loop mode the loop shouldn't be energized when the local circuit is open (to keep the sounder from following the key) and in Key/Paddle & Sounder modes the code shouldn't send the key input to the sounder.

**Comment by leskerr** [comment]
Patrick,

I'm really looking forward to using your Preferences panel. Here are a few comments. They're in top-to-down order as they appear on the panel, not in order of how important I think they are.

1. This first one's a nit. I'd be more comfortable if Serial Port came before GPIO interface. It's the option most users will be looking for, at least for the foreseeable future.
2. Shouldn't the 'Loop', 'Key & Sounder', and 'Keyer paddle' options apply to the GPIO interface as well as the serial interface? I for one would like to be able to connect a key and sounder driver directly to the GPIO pins of a Pi without having to go through an adapter cable to a USB port.
3. I should probably know this already, but what does 'Repeat key input locally' do? Isn't this the function of the 'Key & Sounder' interface?
4. Another nit: I think it would be clearer to say 'Server' rather than 'HostName'. This is an advanced feature though, so it's probably not terribly important. Advanced users will know what it's for.
5. I know why you say 'Initial' on the wire number and code speed options, but personally I'd leave off the 'Initial' part. As it stands, the implication is if I change the value and save it, it only has effect the next time I start the program. I'd much rather have any changes on the preference panel take effect immediately. In the case of these particular options, the changes would be reflected in the main GUI window.
6. Like it or not, we're going to have to revisit the terminology of 'code speed' and 'character rate'. Both terms are ambiguous. I don't have a good solution at the moment.

The preferences panel in its current form is something I can hardly wait to use. However, the complexity is going to be too much for many users. Before releasing the program for general use, I believe we'll want to restructure the preference panel so that only the basic options appear unless the user specifically requests the advanced options.

Finally, and I know this is controversial, I really want the settings on the main GUI window to be temporary ('non-sticky') -- at least until I've had a chance to try it. I know Chris and Chip feel differently, and I understand why, but I very much want to see how well it would work in practice.

**Comment by AESilky** [comment]
Responding to @leskerr 's comment...

1. I agree. I also proposed something in issue #223 to use a 'special' value for the 'Port' value that would indicate that it is a Raspberry Pi. In addition, it could indicate the 'Loop' number ("Loop" is a misnomer, as it could also be the pair of pins used for a key & sounder). That would eliminate the need to a separate option for the physical interface.
2. If we use the proposed solution for #1, then this goes away, as the option applies equally to either physical interface specified by the 'Port' value.
3. I had forgotten about this as well, but it basically means that the local key shouldn't be sounded locally. In the code that means that if it is a Loop interface the loop shouldn't be energized (so the sounder doesn't follow the key), if it is a Key&Sounder interface the key input shouldn't be echoed to the sounder. In both cases, the simulated sounder (computer audio) should not be sounded to follow the key.
4. Beyond the suggestion of 'Server', I might say 'KOB Server' or 'MorseKOB Server'.
5. I agree with Les. I would like changes in the preference window to take effect when I 'OK' out of the window. At the same time, I would like changes I make in the main GUI to be local (not saved). So, for example, if I use the configuration/preferences window to set the wire to '11', that should be saved as the default, and will be the wire value when I start a new instance of the app. If I change the wire value in the main GUI to 105, that should be transient (local to the currently running instance of the app and shouldn't affect other running instances and shouldn't be saved).

@leskerr To be fair to Patrick, I think the initial suggestion was to implement a single window with all options. That is a great start/improvement for beta testers (rather than having to use `Configure.py` to set values).

@pwdirks How hard is it to do tabs? Could we have a 'General' and 'Advanced' tab. Otherwise a 'General'/'Typical' window and then an 'Advanced' window.

**Comment by pwdirks** [comment]
Hi Les,

> On Jan 7, 2021, at 5:20 PM, Les Kerr <notifications@github.com> wrote:
> 
> 
> Patrick,
> 
> I'm really looking forward to using your Preferences panel. Here are a few comments. They're in top-to-down order as they appear on the panel, not in order of how important I think they are.
> 
> This first one's a nit. I'd be more comfortable if Serial Port came before GPIO interface. It's the option most users will be looking for, at least for the foreseeable future.
I laid it out that way so that the “Serial” option could immediately roll into the various “serial”-specific options (loop/sounder/keyer).  It sounds like perhaps doing away with a “Local Interface” (hardware type) selection is preferable anyway?  Opinions?
> Shouldn't the 'Loop', 'Key & Sounder', and 'Keyer paddle' options apply to the GPIO interface as well as the serial interface? I for one would like to be able to connect a key and sounder driver directly to the GPIO pins of a Pi without having to go through an adapter cable to a USB port.
Ah - you’re probably right.  Then the “interface type” just becomes another first-class option.  I can do that.
> I should probably know this already, but what does 'Repeat key input locally' do? Isn't this the function of the 'Key & Sounder' interface?
I think that was an option Ed requested to have keyboard-input still activate the sounder?  Ed?
> Another nit: I think it would be clearer to say 'Server' rather than 'HostName'. This is an advanced feature though, so it's probably not terribly important. Advanced users will know what it's for.
I’m easy.  Unless anyone else has strong feelings on the topic, I’ll re-label it to “Server” or “Server URL”?  We don’t expect a URL-type like “http:”, though, right?  Just a DNS name?
> I know why you say 'Initial' on the wire number and code speed options, but personally I'd leave off the 'Initial' part. As it stands, the implication is if I change the value and save it, it only has effect the next time I start the program. I'd much rather have any changes on the preference panel take effect immediately. In the case of these particular options, the changes would be reflected in the main GUI window.
Hmmm… I’d hoped to avoid creating a situation where you could change the current wire either from the main window OR from the config panel, especially because that introduces confusion about what will end up in the config file if the main window control is not “sticky” but only the “Preferences”/“Options” dialog changes the wire used the next time it’s started?  Almost better to make both wire change modes change the config, or none if “Initial” is not the expected mode of use?
> Like it or not, we're going to have to revisit the terminology of 'code speed' and 'character rate'. Both terms are ambiguous. I don't have a good solution at the moment.
I remember quite a bit of discussion on that.  I don’t find the current terms (“minimum character speed” and “text speed”, I believe) very helpful.  To me at least, “code speed” speaks directly to how short dots and dashes are, and “character rate” pretty clearly suggests the rate at which characters appear.

I’m open to suggestions for clearer terms, though!
> The preferences panel in its current form is something I can hardly wait to use. However, the complexity is going to be too much for many users. Before releasing the program for general use, I believe we'll want to restructure the preference panel so that only the basic options appear unless the user specifically requests the advanced options.
> 
I’m expecting to make such a refinement but I’d probably prefer breaking out some options into a separate “Advanced” dialog as a separate change.
> Finally, and I know this is controversial, I really want the settings on the main GUI window to be temporary ('non-sticky') -- at least until I've had a chance to try it. I know Chris and Chip feel differently, and I understand why, but I very much want to see how well it would work in practice.
> 
I expect to try that model first.  It interacts somewhat with whether “Preferences” changes to wire # or code speed, for instance, affect the values currently in use via the main window and whether one or the other, both, or neither affect the configured values the program starts with the next time.  Besides users who typically want to start on wire 11 or some headlines wire, I think the strongest case for a non-sticky, consistent wire # and code speed at startup is the museum use case.  I’d think it advantageous if the main window could be twiddles by visitors to their heart’s content while powering off the display and re-powering it the next day will still guarantee a consistent startup setting but Chris seems to disagree with that expectation.

Thanks for the feedback!

73, N6PWD
-Patrick.

**Comment by leskerr** [comment]
> 3. I had forgotten about this as well, but it basically means that the local key shouldn't be sounded locally. In the code that means that if it is a Loop interface the loop shouldn't be energized (so the sounder doesn't follow the key), if it is a Key&Sounder interface the key input shouldn't be echoed to the sounder. In both cases, the simulated sounder (computer audio) should not be sounded to follow the key.

There must be a rationale for this option that I'm not seeing. If you don't want to hear your key locally, you can uncheck the 'system sound' and 'local sounder' options. Is there a situation where you'd want to hear the Morse coming from the keyboard or the internet but not what's being sent on your local key?

> @pwdirks How hard is it to do tabs? Could we have a 'General' and 'Advanced' tab. Otherwise a 'General'/'Typical' window and then an 'Advanced' window.

A separate 'Advanced' tab on the Preferences panel would be fantastic! But that's for the future. Let's implement the single panel as soon as possible.

**Comment by leskerr** [comment]
>> Another nit: I think it would be clearer to say 'Server' rather than 'HostName'. This is an advanced feature though, so it's probably not terribly important. Advanced users will know what it's for.

> I’m easy. Unless anyone else has strong feelings on the topic, I’ll re-label it to “Server” or “Server URL”? We don’t expect a URL-type like “http:”, though, right? Just a DNS name?

Right, just a host name. No 'http'.

>> Like it or not, we're going to have to revisit the terminology of 'code speed' and 'character rate'. Both terms are ambiguous. I don't have a good solution at the moment.

> I remember quite a bit of discussion on that. I don’t find the current terms (“minimum character speed” and “text speed”, I believe) very helpful. To me at least, “code speed” speaks directly to how short dots and dashes are, and “character rate” pretty clearly suggests the rate at which characters appear. I’m open to suggestions for clearer terms, though!

'Code speed' to me, with no further clarification, means the 'overall code speed'. In other words, if I'm copying text at a code speed of 20 words per minute, that means I copy twenty words every minute. The individual characters may be sent quickly with extra space between them, but I'm still copying code at 20 wpm.

'Character rate' is not so clear. Does it mean the number of characters I'm copying per minute? Or is it the rate of dots and dashes within each character. It's a problem. sigh...

**Comment by AESilky** [comment]
I think I suggested the 'Local Copy' option early on. I think we can drop it. I don't think any of the code currently uses it (yet to be implemented), so let's remove it.

I can add that to #223 to add a new option and remove that one.

**Comment by AESilky** [comment]
@pwdirks I agree that all options on one page gets us going and we can move things to an 'Advanced' tab/page later.

**Comment by pwdirks** [comment]
Anything remaining here?  If not, shall I file a separate issue to divide 'preferences' content between a 'General' and 'Advanced Settings' tab and close this issue?

**Comment by AESilky** [comment]
I think this is good for now. I'm working on the 'pick up updates' #236.

**Comment by pwdirks** [comment]
Basic preferences window has been merged to master; created issue #249, "Config/preferences should be split into General/basic and a separate "Advanced" tab", to follow up separating basic/advanced preferences into individual tabs.
