### ISSUE TITLE
Les needs to learn GitHub

### ISSUE THREAD

**Issue by leskerr** [MorseKOB/PyKOB#18]
When I have questions about GitHub, should I post them to this 'issues' thread? In particular, I don't know if I should @mention you guys when I post an issue, and/or follow up with a comment. As an experiment, I'll mention @AESilky here and see what happens. Patrick, did you get a notification of this issue?

By the way, I'm using GitHub Desktop to post this issue.

**Comment by leskerr** [comment]
When I said I was using GitHub Desktop, that was an illusion. When I asked GitHub Desktop to create an issue, it actually took me into the GitHub web interface, which I didn't realize at the time.

**Comment by pwdirks** [comment]
Les, I got an email from "Les Kerr <notifications@github.com>" when you created this issue with the text of the issue, even without being at-mentioned.  Creating an issue is enough to notify every member of MorseKOB / pykob-4, I believe.

I'd say, if there's something that needs to be changed in the code or the project, just create an issue.  If there's meta-discussion that needs to happen (e.g. "Should I stop filing issues here and create a new project?") we can do that in e-mail.  Let's see if we can bias anything on the topic of the issue (including "I don't have a sounder to test out this change" or "@so-and-so can you look into this one ASAP since it's blocking my progress") to be done in the issue itself?

**Comment by AESilky** [comment]
Creating the issue will notify those that are following the repo (which I believe are all are now). If you weren't following the repo then you wouldn't be notified unless you are @ mentioned.

Even if we are all following the repo (and therefore being notified), if you specifically want one of us to look at something it is a good idea to @ mention.

**Comment by AESilky** [comment]
Patrick's proposal is fine with me.

**Comment by leskerr** [comment]
I'm still learning, but I think I've made good progress so I'm closing this issue.

**Comment by AESilky** [comment]
I think you are A+. I've been using GitHub for years - and I'm still learning.
I think learning the CLI is important, as that lets you use it across Windows, Linux, Mac.

**Comment by pwdirks** [comment]
> I'm still learning, but I think I've made good progress so I'm closing this issue.

@leskerr I completely agree it's time to but it doesn't look like the issue actually got closed?

I'll let you do the honors.

**Comment by leskerr** [comment]
I sure thought I closed this issue. Maybe it got reopened somehow? I'm going to try doing the same thing one more time.

**Comment by AESilky** [comment]
It is now closed. Very good!
