### ISSUE TITLE
MKOB: When a paragraph char is received the reader should insert a double newline

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#181]
When receiving code, if a paragraph mark is received, the reader window should create a new paragraph (insert a double new-line).

**Comment by AESilky** [comment]
A recent change now has para it inserting a single newline. That is probably fine.

I also think that typing enter/return in the sender window should send a Paragraph 'da da da dah' (rather than having to type a '=').

**Comment by leskerr** [comment]
I think it's fine the way it is. I'm not sure about sending a paragraph mark when you press Enter on the keyboard. I'm in the habit of starting a new line when I end a transmission with the keyboard, and I wouldn't want to send a paragraph mark in that situation.

Also, if you're sending from a text file, it's liable to have random newlines in it. Of course that's not the same thing as actually typing an Enter/Return on the keyboard, but still...

**Comment by jchausler** [comment]
Hi Les and Ed,Something else about the paragraph mark in 4.0 which sort of bothers me.  Every time someone sends a paragraph mark, 4.0 does a newline.  The problem is there are several folks on the wire (Larry Card is one) most of whom I believe are active hams who when thinking of what to say next send several of these in sequence.  Unfortunately, 4.0 does a newline for each which generates a lot of whitespace on the display when these folks are sending. A better algorithm for this would be to only generate the newline when the first non paragraph character is decoded after one or more paragraph characters.  Just my humble opinion.-----Original Message-----

**Comment by AESilky** [comment]
That sounds good.

**Comment by AESilky** [comment]
It now inserts a single paragraph newline when one or more paragraph marks ('=') are received, as soon as a non-paragraph mark is received.
