### ISSUE TITLE
Feed.py: Add ability to use a PyKOB recorder file as a source

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#219]
PyKOB added a recorder file in JSON format. The current `Feed.py` app can source an RSS file/feed. It would be useful for it to also accept a PyKOB recording (.json) file to use as the content to feed.

If a PyKOB recording file is specified, the content should be repeated with a short delay.

**Comment by AESilky** [comment]
I have this working for a feed on my server. It is feeding a PyKOB recording of Instructograph Tape 5 (railroad operations).

**Comment by leskerr** [comment]
I listened to this feed last night and I noticed a few things that I wouldn't have expected from an Instructograph tape.

- The characters are sent very quickly, but with quite a bit of space between the characters. I didn't check the timing, but it sounded like the characters were sent at 30 or 35 wpm. With the spaces, it sounded very jerky to me, although you could argue they were just including Farnsworth spacing.
- Some dots got dropped. I bet the holes were in the tape, but the speed is so fast that maybe some dots were less than MKOB's debounce filter threshold (15ms).
- I noticed at least one instance where an error was sent and then corrected after sending a question mark. This would be expected if the sender was a live operator, but surprising in machine-sent Morse.
- My code readers (both 2.5 and 4.0) had trouble. I'd expect them to be perfect on Instructograph tapes. Adjusting the WPM setting didn't completely solve the problem. There was trouble with the spaced 'Morse letters' and distinguishing 'E' from 'T'.

When I get a chance I'll analyze this more carefully, but I wanted to give some quick feedback.

**Comment by AESilky** [comment]
I noticed the 'error' and '? correction' too. I assumed they did that to help teach you that is to be expected. I also noticed 'T' for 'L' quite a bit in the decoded text. In fact, I'm not sure I ever saw an 'L'.

I'm going to record it again with the machine speed slowed down some. That might help pick up the missing dots. I did a thorough cleaning of the machine including the contacts, but it's very possible that it could use some more adjustment. I would really like to put an optical reader on it, as that shouldn't have a problem missing dots and would be gentler on the tapes, but there have been too many other things going on.

Before you spend a lot of time analyzing it, let me record it again. I can probably do that today or tomorrow.

**Comment by AESilky** [comment]
I re-recorded tape 5 with the speed set to the middle of the speed control.
I had my MKOB set to 28 and it did a pretty good job of decoding it.
I put the recording in the recordings folder on OneDrive:
https://1drv.ms/f/s!AqnBbsz_ABrPhZZxJXVv7IaZ2JNX0Q
That way you can take a look directly.

I'll move this up to my server for my feed, since it does seem much better.

-Ed

**Comment by AESilky** [comment]
What does "SIG KCK" mean?

**Comment by AESilky** [comment]
I don't know why it didn't put a station name in the recording. I had it
set to 'Instructograph Tape 5.1' for the first side and 'Instructograph
Tape 5.2' for the second. That won't effect the code, but I'll record again
later to get the names in.

-Ed

**Comment by AESilky** [comment]
"SIG KCK" = "Signed KCK"
Makes sense.

**Comment by jchausler** [comment]
It turns out that in the set of American Morse tapes, I have, I have three copies of tape 5.  Two are in good shape and one is rather beat and what's further the quality of the punching was poor.  Side on of the tape had an additional dot punched in front of the three I's.  I have a couple of copies of another of the tapes and I've seen where there were errant dots either punched or missing so they did have some quality control issues.

Yes, the KCK is the initials of the dispatcher.  Either SIG or just SG would be sent ahead of the initials (or with commercial telegrams an entire name).  This was basically the marker between the body of the message and the signature.  The SIG or SG was not copied on the message form.  

I have both .pdf's and an original copy of the 1931 Instructograph manual which includes the complete text of American Morse tape 5.  If any of you wants a copy let me know.  The .pdf is about 13MB but I think that will squeeze through an email.

I also took tape 5 and my instructograph and ran tape five into a copy of MorseKOB.  With the WPM set to 24 I found that as the tape ran I had to slow it down a bit to keep the decoding accurate as of course as the diameter of the take up spool gets larger as the tape winds on it the actual speed of the tape increases with no change in the speed setting.  I got pretty good decoding but it did have problems with some of the spaced characters.

I took a steel rule and measured the length of the various punches and spaces between them.  I measured from the edges in the middle of the round cuts.  As best as I can tell to the nearest 64th of an inch here are the sizes.  Dot 5/64, Intracharacter space 7/64, Dash 23/64, spaced character space 17/64, Intercharacter space 35/64 and long dash (L) also 35/64.  I didn't measure the zero but it is even longer than the L.  So yes, there is some Farnsworth and one can see where running it much faster might cause the dots to be missed.  I think I said this earlier but I found to hear decent code from an instructograph one had to very carefully and tediously adjust the contact head and spring tension and position.  So dots are probably less than half as long as they should be.

73, Chris

**Comment by leskerr** [comment]
Chris, I would love to see that Instructograph manual. Ed, is that something Chris could upload to your OneDrive account at https://onedrive.live.com/?authkey=%21AOOF%2D3ZQp5ezeTw&id=CF1A00FFCC6EC1A9%2184808&cid=CF1A00FFCC6EC1A9?

~Les

**Comment by AESilky** [comment]
I would love to see it as well. I have the 1-2 pages sheets there were included. I reproduced them and put them on the OneDrvie location. I don't have the full manual with the text.

@jchausler I will send you an email with a link that lets you edit (add to) the 'Instructograph' folder. You can access that with a browser and simply upload it.

The Instructograph info I have pulled together is there as well as the recordings I've made so far. I would like to add an opto encoder to my machine so it can read the tape rather than using the mechanical stylus and contact. I think that would really help in the playback of the tapes as well as keep them from getting worn. My tapes don't appear to have been played very much at all and it would be nice to keep them that way.

The public (read only) link to 'Instructograph' is: https://1drv.ms/f/s!AqnBbsz_ABrPhZZIJXVv7IaZ2JNX0Q
My overall public (read only) link is: https://1drv.ms/f/s!AqnBbsz_ABrPhKxtioseUvEHPkIBwA
There is a 'MorseKOB' folder there that contains different things I've pulled together.

**Comment by AESilky** [comment]
I notice that comments in the pull request/review are not copied here. It would be benefitial to have most of them here. Refer to Pull Request #222 for more complete/specific comments.

**Comment by AESilky** [comment]
I am looking at Python and 'file://' URL operations.

That is pretty straightforward in C# and Java, should be the same in Python. I'm sure it is, just trying to find it.

**Comment by AESilky** [comment]
The hard thing is that in Mac & Linux it 'just works'. It is only with Windows that using 'file://...' doesn't work as a local file path.

I'm trying to track down how to handle 'file://...' in python, but I might put in a temporary fix that treats 'non-absolute' file path references as a RSS reference. If a recording (_pykob_.json file) is accessed using a 'http://' or 'file://' URL it will be (incorrectly) categorized as an RSS feed.

**Comment by jchausler** [comment]
I have uploaded the Instructograph manual to Ed's One Drive page.  I'm assuming everyone in the project can access it from there.  The data on American Morse tape 5 is on pages 46 and 47 of the .pdf (44 and 45 in the original manual).  If I need to send it out elsewise, please let me know.  The section of the manual on American Morse starts on page 38 in the .pdf (36 original).

Yes, an optical pick up head might improve the decoding but as one who has had long experience (but long past :-) of reading oiled (8-level) tapes with an optical reader, you have to be very careful with the light intensity and sensitivity of the pick up as it is easier for the pick up to "see through" the somewhat translucent tape than the opaque (and not oiled) tape for which most optical readers were intended.  I can tell you stories :-)  Also the oiled tape tends to pick up dirt and then deposit a sticky combination of dirt, paper flakes and hardened oil on the pick up.  Regular cleaning is suggested.

73, Chris

**Comment by AESilky** [comment]
Hi Chris,

Yes, I can see it there. That is fantastic. Yes, not only people in this
project, but actually anyone can see it there. That portion of my OneDrive
is open to the public. Please don't share the link I gave you (as that
allows editing), but please feel free to share:
https://1drv.ms/f/s!AqnBbsz_ABrPhKxwJXVv7IaZ2JNX0Q
That is a link to all of the MorseKOB info I have collected. That includes
the Instructograph stuff as well as Dial-Up Morse and Wire-11 stuff.

-Ed
