### ISSUE TITLE
MKOB: Tkinter exception: 'Spinbox'

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#232]
Running in Linux, I got the following exception:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/ed/code/morse/PyKOB/kobactions.py", line 79, in doFilePreferences
    prefs = preferencesWindow.PreferencesWindow(quitWhenDismissed=False)
  File "/home/ed/code/morse/PyKOB/pykob/preferencesWindow.py", line 186, in __init__
    ttk.Spinbox(codeOptions, from_=1, to=99,
AttributeError: module 'tkinter.ttk' has no attribute 'Spinbox'
```

**Comment by pwdirks** [comment]
Hi Ed,

That’s very strange - it should be a standard part of ttk.py - see https://docs.python.org/3/library/tkinter.ttk.html#ttk-spinbox <https://docs.python.org/3/library/tkinter.ttk.html#ttk-spinbox> for documentation.

I’ve also seen references to ttk.spinbox (with a lowercase “s”).  Is that used in your ttk.py definitions by chance?

It works for me on macOS, obviously, and seems to work OK on Windows.  Is it perhaps unique to the Linux environment you have set up?  Do you have an up-to-date Python 3 installed there?

73, -Patrick.

**Comment by pwdirks** [comment]
My Ubuntu VM, BTW, has Python 3.8 and Python 3.9 installed and /usr/lib/python3.8/tkinter/ttk.py includes a definition of "Spinbox" (with a capital "S").  I'm mystified why it should fail on your system where it does because by that time it's already instantiated a number of other TTK types (ttk.LabelFrame, ttk.ComboBox, and others).

Can you have a look in your ttk.py file sometime and see what's there?

**Comment by AESilky** [comment]
I will take a look later today when I'm at my Linux box.

**Comment by AESilky** [comment]
This has been working in multiple Linux environments, so closing it.
