### ISSUE TITLE
In 'Separate key and sounder' mode, the sounder does not follow the key in real time.

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#288]
Instead of following the key openings and closings the instant they happen, MKOB waits for a complete character to be sent before replicating it on the sounder. In fact, if I send a string of ten or fifteen dots, the sounder doesn't do anything until I stop sending.

**Comment by pwdirks** [comment]
﻿
Hi Ed,

I wonder if that’s actually unhelpful for local senders.  Maybe an item on the “Issues List” could be created to make the local sounder (or its simulation) more directly track the key input?

Cheers,
-Patrick.

**Comment by jchausler** [comment]
Hi Ed,

I agree, the sounder, whether real or simulated, needs to follow the key operations click by click, now the screen decoder likely needs to wait for a pause to be able to determine the last character sent and that includes a long string of just dots.  I just checked and 2.5 appears to work this way.

73, Chris
-----Original Message-----

**Comment by AESilky** [comment]
Patrick and Chris,

I'm not sure about your comments.

This issue is for the problem that the sounder doesn't directly follow the key. In fact, it waits until a full character has been decoded before sounding anything.

My fix is to move the sounder activation directly into the key handling code. With that change, I can't detect any delay by listening to it. I am currently doing some more testing and plan to hook up my scope so I can measure it (like I did for issue #158).

This issue (#288) is for a physical key, and #158 (Speaker lags key) is for the virtual sounder (it's been open for quite some time).

**Comment by AESilky** [comment]
I was busy today and will be tomorrow and Tuesday as well. I should be able to wrap up my testing and merge in my fix Wednesday or Thursday.

**Comment by jchausler** [comment]
Hi Ed,

I think what you are saying is what I was suggesting.  That the sounder actuations, simulated or real, should directly follow the key rather than wait for the decode algorithm to figure out what was sent.  In fact as I said I don't think the decode algorithm could even start its task until a complete character is received and so that should be an entirely separate operation.  If you actually just send a connected string of dots, that to the decode routine is just one character.  The original Mill program sort of did the same thing in that it would sound the character and only then show it on the screen.  When I was learning, I found this very valuable as I couldn't verify what the character was until I had first heard it.

Have a happy holiday season!!!

73, Chris
-----Original Message-----

**Comment by AESilky** [comment]
I tested this with a key and the virtual sounder, and Les tested with a key and physical sounder. Everything is working well now.
