### ISSUE TITLE
Clock.py --help isn't clear

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#34]
Using `Clock.py --help` info wasn't clear.

```
Eds-Macbook:PyKOB esilky$ python3 ./clock.py --help
2020-05-11 01:01:47 Starting Clock
usage: clock.py [-h] [-p portname] [-a sound] [-s speed] [-b time] [-e time]
                [-i minutes] [-t]

optional arguments:
  -h, --help            show this help message and exit
  -p portname, --port portname
                        The name of the serial port to use
  -a sound, --sound sound
                        'ON' or 'OFF' to indicate whether morse audio should
                        be generated
  -s speed, --speed speed
                        The morse send speed in WPM
  -b time, --begin time
                        Beginning of time announcements
  -e time, --end time   End of time announcements
  -i minutes, --interval minutes
                        The time announcement interval in minutes
  -t, --text            Whether to print text locally as it's sent to the
                        sounder
Eds-Macbook:PyKOB esilky$ python3 ./clock.py --begin time now
2020-05-11 01:08:55 Starting Clock
usage: clock.py [-h] [-p portname] [-a sound] [-s speed] [-b time] [-e time]
                [-i minutes] [-t]
clock.py: error: argument -b/--begin: invalid int value: 'time'
Eds-Macbook:PyKOB esilky$ 
```
Given the help I tried `python3 clock.py --begin time now`
I also tried `python3 clock.py --begin now`
Neither worked.

I think the help needs to be more specific of the syntax.

**Comment by pwdirks** [comment]
Hi Ed,

I was never quite clear whether the “meta-variable” passed in for an argument was intended to convey the UNITS expected with the parameter (e.g. “--begin <int>”) or the parameter being specified (e.g. “--begin <start-time>”).  The examples I found didn’t use angle brackets, BTW, which I do think are a helpful indication something’s supposed to be “filled in” for that parameter.

The expectation for the “--begin” and “--end" parameter, for instance, is a time like “--begin 900” (I don’t believe 0900 is accepted because that’s the convention for octal numbers), or “--end 2230”.  Can you suggest more helpful help texts?

I believe “--help” generation is automatic, but perhaps there’s a place to work an example into the help text which might also be helpful?

Thanks,
-Patrick.

**Comment by AESilky** [comment]
I'll take a look at the Python doc standards (suggestions) and see if I can
come up with something.

-Ed

**Comment by AESilky** [comment]
In reading through the description of 'argparse', I think `meta-variable` should be something that helps the user understand what should be supplied as a value. I don't think there is a hard-fast rule of it being units or something else. For example, for `--taxtspeed` a `meta-variable` of "wpm" probably helps a user more than "speed" would. For `--port` a `meta-variable` of "port-name/path" is probably more helpful than "port" or "str".

I think the help is now fairly clear (I believe it's been updated since this issue was created). Since I have this file in my current change for #12, I will make a slight change to the help text to indicate that the time is in 24-hour format (0 - 2400).

Then, when I close #12 I'll close this as well.

**Comment by AESilky** [comment]
The changes for #12 resolved this and it has been implemented and merged.

Closing this issue.
