### ISSUE TITLE
Add path to ls

### ISSUE THREAD

**Issue by ChipEckardt** [MorseKOB/PyKOB#369]
Documentation for installing on an Innovato Quadra may be missing having PyKOB/src.py in PATH.  If you run "python3 Configure.py" from /PyKOB you receive errno 2 cannot find file/directory

**Comment by AESilky** [comment]
I updated the instructions (at the beginning of the post in the MorseKOB group: https://groups.io/g/morsekob/topic/98403094) to indicate that the utilities and applications are now in the *src.py* directory (rather than directly in the *PyKOB* directory), and that the name of the MKOB application changed from *MKOB.pyw* to *MKOB.py*. I also mentioned the **MRT** application (the command-line *Morse Receive and Transmit* application).
