### ISSUE TITLE
User preferences - support character speed in core

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#39]
User preferences/configuration allows the user to set a character speed (in Words-Per-Minute).

Update the core to accept and use the character speed value.

**Comment by leskerr** [comment]
@AESilky, I'm really glad you're working on this. I'll have comments for you tomorrow. I hope I'm not slowing you down by not responding more quickly.

**Comment by leskerr** [comment]
Since it's after midnight I guess that qualifies as 'tomorrow', so here are some comments. Unfortunately, I'm not up to speed yet on the internal details of the pykob.config module. A lot of the library routines for argument parsing are unfamiliar to me. If some of my comments are ill-informed, please set me straight.

1) I'm very happy that you're adding the character words per minute to the core. By this, I assume pykob.morse will be modified to get this parameter from the config file, unless it's overridden with an explicit parameter when a code sender instance is created. The same goes for the overall code speed parameter, of course.

2) The spacing parameter should allow for NONE (i.e. no Farnsworth spacing) in addition to CHARACTER and WORD.

3) Sooner or later we'll need a config parameter for the code type (AMERICAN or INTERNATIONAL).

4) I'm struggling to get comfortable with the term _word speed_. It would be unfamiliar and probably confusing to most users. I'd prefer _code speed_ (the commonly used term) or _text speed_ (used in the [Wikipedia article](https://en.wikipedia.org/wiki/Morse_code#Farnsworth_speed) on Farnsworth spacing).

**Comment by pwdirks** [comment]
> 4. I'm struggling to get comfortable with the term word speed. It would be unfamiliar and probably confusing to most users. I'd prefer code speed (the commonly used term) or text speed (used in the Wikipedia article on Farnsworth spacing).

I worry "code speed" will still be confusing if it's NOT intended to be the speed at which the morse code characters are sent.  "Text Speed" seems clear enough, although I'm not thrilled with the term.  "Message speed"?  "Overall speed"?

**Comment by leskerr** [comment]
> > 1. I'm struggling to get comfortable with the term word speed. It would be unfamiliar and probably confusing to most users. I'd prefer code speed (the commonly used term) or text speed (used in the Wikipedia article on Farnsworth spacing).
> 
> I worry "code speed" will still be confusing if it's NOT intended to be the speed at which the morse code characters are sent. "Text Speed" seems clear enough, although I'm not thrilled with the term. "Message speed"? "Overall speed"?

Yeah, it seems to me we're overthinking this by trying to make the definition precise and muddying the issue for most users in the process. I took a look at the [W1AW code practice page](http://www.arrl.org/code-practice-files) to see what language they use. The term _WPM_ appears 40 times on that page with the implied meaning of code/text/message speed, the term _speed_ by itself (with the same meaning) appears twice, and the term _character speed_ is used once to distinguish it from 'normal speed'.

There's no explicit mention of Farnsworth on the W1AW page. It's just their policy to always send characters at a minimum speed of 18 wpm. I think PyKOB should do the same thing, while allowing the option to override it. We should follow the principle of making the normal things simple and the rare things possible.

The Morse News program uses the terms _code speed_ and _char speed_. These make sense to me.

</ rant off>

**Comment by pwdirks** [comment]
I see "transmission speed", "word speed", and "WPM speed" used.  How about if we use, as the original parameters did, just use "WPM" for the overall transmission speed and "CSPEED" or "character speed" for the speed at which individual characters are sent (still specified in the same wpm units), with a FARNSWORTH or SPACING option to specify whether to insert space between characters or between words to make the overall transmission speed (WPM) be as specified?

As for how this should be specified, I believe we're settling on a model where there's a "config" that has defaults for all values, but individual programs can override those defaults as appropriate.  I agree the "default default" or ("default configuration") for CHAR_SPEED should be MAX(18, WPM), with WPM defaulting to, oh, 18?  If you configure WPM to be, say, 25 you get CHAR_SPEED=25; if you configure WPM to be 10 you get "10/18" timing as the ARRL page would describe it: 10 WPM overall, with characters sent at 18 WPM rate?

**Comment by AESilky** [comment]
Although good to have in this issue, I believe much of this should be in the review for #12.
Many of the comments will also apply to this issue when the speed & spacing is implemented in the core.

I am going to copy this to #12 with a mention of this issue for future reference.

**Comment by AESilky** [comment]
This was implemented some time ago. Not sure of the exact version.
