### ISSUE TITLE
MKOB: Received code stops short of that sent

### ISSUE THREAD

**Issue by AESilky** [MorseKOB/PyKOB#74]
The received code window stops two characters short of what is sent on the wire.

For example, when receiving code on a wire where another station sends "ABCDEFG", the received code window shows "ABCDE" (missing the "FG").

Image from MKOB-2.5 (sending) and MKOB-4.0.3 (receiving):
![6-19-2020 10-46-08 PM](https://user-images.githubusercontent.com/19332027/85193766-21274080-b280-11ea-926a-915467db1a1c.png)

**Comment by leskerr** [comment]
MKOB needs to call `pykob.morse.Reader.flush()` after a 'suitable' length of time has passed with no new characters being received. A timer mechanism similar to that used in MorseKOB 2.5 will do the job.

**Comment by AESilky** [comment]
Thanks. That's what I was looking at, but hadn't tried it yet. I'll try
that tonight.

**Comment by AESilky** [comment]
When MKOB-2.5 and MKOB-4.0 are run side-by-side the MKOB-2.5 window is 2 characters ahead of the MKOB-4.0 window.

Unless you have the two open together this probably isn't a big issue. Maybe flushing at a 'reasonable' time after the last character received will resolve this.

**Comment by pwdirks** [comment]
Do we understand the root cause of the delay?  Isn’t the receiving code largely similar?  Is the lagging text added to the display buffer and not shown, or not even added to the display buffer yet?

I’ll be curious to see an update when you find what it takes - I think we should make the two absolutely equal; I DON’T think a 2-character lag would be acceptable to most users.  We want this to be as “real time” as possible.

**Comment by leskerr** [comment]
There are two things going on here. The first is that the code reader needs a timer to determine when the sender has stopped sending and the reader should flush its buffer. Until this feature is added to the program, the last character or two will be pending.

The second is that there's an intentional, roughly one second delay built into the receiving client. This is the way CWCom works, and MorseKOB 2.5 works the same way. The reason for this is to smooth out the jitter that would result if a short letter (such as E) were to be decoded immediately and then followed by a long letter (such as J).

The only problem with having the receiver lag behind the sender is when an operator wants to break in between the transmissions between two other operators. To get around this, the receiving client responds immediately to the initial opening of the circuit and only starts buffering with the first character after the circuit is opened. This is not entirely realistic, but all things considered it seems to be the best compromise.

**Comment by AESilky** [comment]
I agree with Les. The problem with the last two characters is that they are not displayed until another character is received. I started adding a timer that will flush the buffer if a character isn't received for some amount of time (probably just less than a second). 

I was looking at how to correctly incorporate an async timer that can be cancelled/reset/restarted when a new character is received and flush if it expires, but then got pulled away.

I will try to get back on that. If you know OTTOYH let me know and I'll put it in my branch and test it out.
